### ISSUE TITLE
Contact page 

### ISSUE THREAD

**Issue by mukulaggy** [pccoe-acm-hacktoberfest-2023/GDSC_ecommerce_istop_dummywebsite#5]
implement Bootstrap/external CSS to add contact details in contact page

**Comment by AryaKale16** [comment]
Hey @mukulaggy ,
I would like to work on this issue and add the required CSS, here is my profile: [link](http://aryakale.me/)
Kindly consider assigning this issue to me.

**Comment by mukulaggy** [comment]
@AryaKale16 we will not assign the project to anyone just work on it and raise a PR ,if found good we will merge it.
